sudo: false
language: node_js
node_js:
  - v6
  - v5
  - v4

before_install:
  - npm install --global gulp-cli bower

install:
  - npm install
  - bower install

script: gulp

after_success:
  - gulp deploy --host HOST --user USERNAME --password PASSWORD
