sudo: false
language: node_js
node_js:
  - node

before_install:
  - npm install --global gulp-cli bower

install:
  - npm install
  - bower install

script: gulp

after_success:
  - gulp deploy --host $HOST --user $USERNAME --password $PASSWORD
